// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package net.protol.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface test4OrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.test4)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 f = 1;</code>
     */
    int getF();

    /**
     * <code>string ccc = 2;</code>
     */
    java.lang.String getCcc();
    /**
     * <code>string ccc = 2;</code>
     */
    com.google.protobuf.ByteString
        getCccBytes();

    /**
     * <code>string cmd_data = 3;</code>
     */
    java.lang.String getCmdData();
    /**
     * <code>string cmd_data = 3;</code>
     */
    com.google.protobuf.ByteString
        getCmdDataBytes();
  }
  /**
   * Protobuf type {@code common.test4}
   */
  public  static final class test4 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.test4)
      test4OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use test4.newBuilder() to construct.
    private test4(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private test4() {
      f_ = 0;
      ccc_ = "";
      cmdData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private test4(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              f_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ccc_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cmdData_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.protol.common.Common.internal_static_common_test4_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.protol.common.Common.internal_static_common_test4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.protol.common.Common.test4.class, net.protol.common.Common.test4.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    private int f_;
    /**
     * <code>int32 f = 1;</code>
     */
    public int getF() {
      return f_;
    }

    public static final int CCC_FIELD_NUMBER = 2;
    private volatile java.lang.Object ccc_;
    /**
     * <code>string ccc = 2;</code>
     */
    public java.lang.String getCcc() {
      java.lang.Object ref = ccc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ccc_ = s;
        return s;
      }
    }
    /**
     * <code>string ccc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCccBytes() {
      java.lang.Object ref = ccc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ccc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object cmdData_;
    /**
     * <code>string cmd_data = 3;</code>
     */
    public java.lang.String getCmdData() {
      java.lang.Object ref = cmdData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmdData_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd_data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCmdDataBytes() {
      java.lang.Object ref = cmdData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (f_ != 0) {
        output.writeInt32(1, f_);
      }
      if (!getCccBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ccc_);
      }
      if (!getCmdDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmdData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (f_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, f_);
      }
      if (!getCccBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ccc_);
      }
      if (!getCmdDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmdData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.protol.common.Common.test4)) {
        return super.equals(obj);
      }
      net.protol.common.Common.test4 other = (net.protol.common.Common.test4) obj;

      boolean result = true;
      result = result && (getF()
          == other.getF());
      result = result && getCcc()
          .equals(other.getCcc());
      result = result && getCmdData()
          .equals(other.getCmdData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + getF();
      hash = (37 * hash) + CCC_FIELD_NUMBER;
      hash = (53 * hash) + getCcc().hashCode();
      hash = (37 * hash) + CMD_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getCmdData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.protol.common.Common.test4 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test4 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test4 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test4 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test4 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test4 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test4 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.test4 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test4 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.test4 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test4 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.protol.common.Common.test4 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.test4}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.test4)
        net.protol.common.Common.test4OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.protol.common.Common.internal_static_common_test4_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.protol.common.Common.internal_static_common_test4_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.protol.common.Common.test4.class, net.protol.common.Common.test4.Builder.class);
      }

      // Construct using net.protol.common.Common.test4.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        f_ = 0;

        ccc_ = "";

        cmdData_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.protol.common.Common.internal_static_common_test4_descriptor;
      }

      public net.protol.common.Common.test4 getDefaultInstanceForType() {
        return net.protol.common.Common.test4.getDefaultInstance();
      }

      public net.protol.common.Common.test4 build() {
        net.protol.common.Common.test4 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.protol.common.Common.test4 buildPartial() {
        net.protol.common.Common.test4 result = new net.protol.common.Common.test4(this);
        result.f_ = f_;
        result.ccc_ = ccc_;
        result.cmdData_ = cmdData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.protol.common.Common.test4) {
          return mergeFrom((net.protol.common.Common.test4)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.protol.common.Common.test4 other) {
        if (other == net.protol.common.Common.test4.getDefaultInstance()) return this;
        if (other.getF() != 0) {
          setF(other.getF());
        }
        if (!other.getCcc().isEmpty()) {
          ccc_ = other.ccc_;
          onChanged();
        }
        if (!other.getCmdData().isEmpty()) {
          cmdData_ = other.cmdData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.protol.common.Common.test4 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.protol.common.Common.test4) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int f_ ;
      /**
       * <code>int32 f = 1;</code>
       */
      public int getF() {
        return f_;
      }
      /**
       * <code>int32 f = 1;</code>
       */
      public Builder setF(int value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 f = 1;</code>
       */
      public Builder clearF() {
        
        f_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ccc_ = "";
      /**
       * <code>string ccc = 2;</code>
       */
      public java.lang.String getCcc() {
        java.lang.Object ref = ccc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ccc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ccc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCccBytes() {
        java.lang.Object ref = ccc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ccc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ccc = 2;</code>
       */
      public Builder setCcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ccc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ccc = 2;</code>
       */
      public Builder clearCcc() {
        
        ccc_ = getDefaultInstance().getCcc();
        onChanged();
        return this;
      }
      /**
       * <code>string ccc = 2;</code>
       */
      public Builder setCccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ccc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmdData_ = "";
      /**
       * <code>string cmd_data = 3;</code>
       */
      public java.lang.String getCmdData() {
        java.lang.Object ref = cmdData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmdData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd_data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCmdDataBytes() {
        java.lang.Object ref = cmdData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd_data = 3;</code>
       */
      public Builder setCmdData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmdData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd_data = 3;</code>
       */
      public Builder clearCmdData() {
        
        cmdData_ = getDefaultInstance().getCmdData();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd_data = 3;</code>
       */
      public Builder setCmdDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmdData_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.test4)
    }

    // @@protoc_insertion_point(class_scope:common.test4)
    private static final net.protol.common.Common.test4 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.protol.common.Common.test4();
    }

    public static net.protol.common.Common.test4 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<test4>
        PARSER = new com.google.protobuf.AbstractParser<test4>() {
      public test4 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new test4(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<test4> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<test4> getParserForType() {
      return PARSER;
    }

    public net.protol.common.Common.test4 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface test3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.test3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 d = 1;</code>
     */
    int getD();

    /**
     * <code>.common.test4 cc = 2;</code>
     */
    boolean hasCc();
    /**
     * <code>.common.test4 cc = 2;</code>
     */
    net.protol.common.Common.test4 getCc();
    /**
     * <code>.common.test4 cc = 2;</code>
     */
    net.protol.common.Common.test4OrBuilder getCcOrBuilder();
  }
  /**
   * Protobuf type {@code common.test3}
   */
  public  static final class test3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.test3)
      test3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use test3.newBuilder() to construct.
    private test3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private test3() {
      d_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private test3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              d_ = input.readInt32();
              break;
            }
            case 18: {
              net.protol.common.Common.test4.Builder subBuilder = null;
              if (cc_ != null) {
                subBuilder = cc_.toBuilder();
              }
              cc_ = input.readMessage(net.protol.common.Common.test4.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cc_);
                cc_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.protol.common.Common.internal_static_common_test3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.protol.common.Common.internal_static_common_test3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.protol.common.Common.test3.class, net.protol.common.Common.test3.Builder.class);
    }

    public static final int D_FIELD_NUMBER = 1;
    private int d_;
    /**
     * <code>int32 d = 1;</code>
     */
    public int getD() {
      return d_;
    }

    public static final int CC_FIELD_NUMBER = 2;
    private net.protol.common.Common.test4 cc_;
    /**
     * <code>.common.test4 cc = 2;</code>
     */
    public boolean hasCc() {
      return cc_ != null;
    }
    /**
     * <code>.common.test4 cc = 2;</code>
     */
    public net.protol.common.Common.test4 getCc() {
      return cc_ == null ? net.protol.common.Common.test4.getDefaultInstance() : cc_;
    }
    /**
     * <code>.common.test4 cc = 2;</code>
     */
    public net.protol.common.Common.test4OrBuilder getCcOrBuilder() {
      return getCc();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (d_ != 0) {
        output.writeInt32(1, d_);
      }
      if (cc_ != null) {
        output.writeMessage(2, getCc());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (d_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, d_);
      }
      if (cc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCc());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.protol.common.Common.test3)) {
        return super.equals(obj);
      }
      net.protol.common.Common.test3 other = (net.protol.common.Common.test3) obj;

      boolean result = true;
      result = result && (getD()
          == other.getD());
      result = result && (hasCc() == other.hasCc());
      if (hasCc()) {
        result = result && getCc()
            .equals(other.getCc());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + D_FIELD_NUMBER;
      hash = (53 * hash) + getD();
      if (hasCc()) {
        hash = (37 * hash) + CC_FIELD_NUMBER;
        hash = (53 * hash) + getCc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.protol.common.Common.test3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.test3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.test3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.test3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.test3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.test3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.protol.common.Common.test3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.test3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.test3)
        net.protol.common.Common.test3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.protol.common.Common.internal_static_common_test3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.protol.common.Common.internal_static_common_test3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.protol.common.Common.test3.class, net.protol.common.Common.test3.Builder.class);
      }

      // Construct using net.protol.common.Common.test3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        d_ = 0;

        if (ccBuilder_ == null) {
          cc_ = null;
        } else {
          cc_ = null;
          ccBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.protol.common.Common.internal_static_common_test3_descriptor;
      }

      public net.protol.common.Common.test3 getDefaultInstanceForType() {
        return net.protol.common.Common.test3.getDefaultInstance();
      }

      public net.protol.common.Common.test3 build() {
        net.protol.common.Common.test3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.protol.common.Common.test3 buildPartial() {
        net.protol.common.Common.test3 result = new net.protol.common.Common.test3(this);
        result.d_ = d_;
        if (ccBuilder_ == null) {
          result.cc_ = cc_;
        } else {
          result.cc_ = ccBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.protol.common.Common.test3) {
          return mergeFrom((net.protol.common.Common.test3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.protol.common.Common.test3 other) {
        if (other == net.protol.common.Common.test3.getDefaultInstance()) return this;
        if (other.getD() != 0) {
          setD(other.getD());
        }
        if (other.hasCc()) {
          mergeCc(other.getCc());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.protol.common.Common.test3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.protol.common.Common.test3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int d_ ;
      /**
       * <code>int32 d = 1;</code>
       */
      public int getD() {
        return d_;
      }
      /**
       * <code>int32 d = 1;</code>
       */
      public Builder setD(int value) {
        
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 d = 1;</code>
       */
      public Builder clearD() {
        
        d_ = 0;
        onChanged();
        return this;
      }

      private net.protol.common.Common.test4 cc_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.protol.common.Common.test4, net.protol.common.Common.test4.Builder, net.protol.common.Common.test4OrBuilder> ccBuilder_;
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public boolean hasCc() {
        return ccBuilder_ != null || cc_ != null;
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public net.protol.common.Common.test4 getCc() {
        if (ccBuilder_ == null) {
          return cc_ == null ? net.protol.common.Common.test4.getDefaultInstance() : cc_;
        } else {
          return ccBuilder_.getMessage();
        }
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public Builder setCc(net.protol.common.Common.test4 value) {
        if (ccBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cc_ = value;
          onChanged();
        } else {
          ccBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public Builder setCc(
          net.protol.common.Common.test4.Builder builderForValue) {
        if (ccBuilder_ == null) {
          cc_ = builderForValue.build();
          onChanged();
        } else {
          ccBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public Builder mergeCc(net.protol.common.Common.test4 value) {
        if (ccBuilder_ == null) {
          if (cc_ != null) {
            cc_ =
              net.protol.common.Common.test4.newBuilder(cc_).mergeFrom(value).buildPartial();
          } else {
            cc_ = value;
          }
          onChanged();
        } else {
          ccBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public Builder clearCc() {
        if (ccBuilder_ == null) {
          cc_ = null;
          onChanged();
        } else {
          cc_ = null;
          ccBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public net.protol.common.Common.test4.Builder getCcBuilder() {
        
        onChanged();
        return getCcFieldBuilder().getBuilder();
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      public net.protol.common.Common.test4OrBuilder getCcOrBuilder() {
        if (ccBuilder_ != null) {
          return ccBuilder_.getMessageOrBuilder();
        } else {
          return cc_ == null ?
              net.protol.common.Common.test4.getDefaultInstance() : cc_;
        }
      }
      /**
       * <code>.common.test4 cc = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.protol.common.Common.test4, net.protol.common.Common.test4.Builder, net.protol.common.Common.test4OrBuilder> 
          getCcFieldBuilder() {
        if (ccBuilder_ == null) {
          ccBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.protol.common.Common.test4, net.protol.common.Common.test4.Builder, net.protol.common.Common.test4OrBuilder>(
                  getCc(),
                  getParentForChildren(),
                  isClean());
          cc_ = null;
        }
        return ccBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.test3)
    }

    // @@protoc_insertion_point(class_scope:common.test3)
    private static final net.protol.common.Common.test3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.protol.common.Common.test3();
    }

    public static net.protol.common.Common.test3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<test3>
        PARSER = new com.google.protobuf.AbstractParser<test3>() {
      public test3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new test3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<test3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<test3> getParserForType() {
      return PARSER;
    }

    public net.protol.common.Common.test3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface client_infoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.client_info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     *
     * <code>string user_name = 7;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     *
     * <code>string user_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     *正在使用的头像
     * </pre>
     *
     * <code>int32 use_icon = 8;</code>
     */
    int getUseIcon();
  }
  /**
   * Protobuf type {@code common.client_info}
   */
  public  static final class client_info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.client_info)
      client_infoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use client_info.newBuilder() to construct.
    private client_info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private client_info() {
      userName_ = "";
      useIcon_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private client_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 64: {

              useIcon_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.protol.common.Common.internal_static_common_client_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.protol.common.Common.internal_static_common_client_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.protol.common.Common.client_info.class, net.protol.common.Common.client_info.Builder.class);
    }

    public static final int USER_NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     *
     * <code>string user_name = 7;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     *
     * <code>string user_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USE_ICON_FIELD_NUMBER = 8;
    private int useIcon_;
    /**
     * <pre>
     *正在使用的头像
     * </pre>
     *
     * <code>int32 use_icon = 8;</code>
     */
    public int getUseIcon() {
      return useIcon_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userName_);
      }
      if (useIcon_ != 0) {
        output.writeInt32(8, useIcon_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userName_);
      }
      if (useIcon_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, useIcon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.protol.common.Common.client_info)) {
        return super.equals(obj);
      }
      net.protol.common.Common.client_info other = (net.protol.common.Common.client_info) obj;

      boolean result = true;
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && (getUseIcon()
          == other.getUseIcon());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USE_ICON_FIELD_NUMBER;
      hash = (53 * hash) + getUseIcon();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.protol.common.Common.client_info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.client_info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.client_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.client_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.client_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.client_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.client_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.client_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.client_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.client_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.client_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.client_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.protol.common.Common.client_info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.client_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.client_info)
        net.protol.common.Common.client_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.protol.common.Common.internal_static_common_client_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.protol.common.Common.internal_static_common_client_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.protol.common.Common.client_info.class, net.protol.common.Common.client_info.Builder.class);
      }

      // Construct using net.protol.common.Common.client_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";

        useIcon_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.protol.common.Common.internal_static_common_client_info_descriptor;
      }

      public net.protol.common.Common.client_info getDefaultInstanceForType() {
        return net.protol.common.Common.client_info.getDefaultInstance();
      }

      public net.protol.common.Common.client_info build() {
        net.protol.common.Common.client_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.protol.common.Common.client_info buildPartial() {
        net.protol.common.Common.client_info result = new net.protol.common.Common.client_info(this);
        result.userName_ = userName_;
        result.useIcon_ = useIcon_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.protol.common.Common.client_info) {
          return mergeFrom((net.protol.common.Common.client_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.protol.common.Common.client_info other) {
        if (other == net.protol.common.Common.client_info.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.getUseIcon() != 0) {
          setUseIcon(other.getUseIcon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.protol.common.Common.client_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.protol.common.Common.client_info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       *
       * <code>string user_name = 7;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       *
       * <code>string user_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       *
       * <code>string user_name = 7;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       *
       * <code>string user_name = 7;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       *
       * <code>string user_name = 7;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private int useIcon_ ;
      /**
       * <pre>
       *正在使用的头像
       * </pre>
       *
       * <code>int32 use_icon = 8;</code>
       */
      public int getUseIcon() {
        return useIcon_;
      }
      /**
       * <pre>
       *正在使用的头像
       * </pre>
       *
       * <code>int32 use_icon = 8;</code>
       */
      public Builder setUseIcon(int value) {
        
        useIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *正在使用的头像
       * </pre>
       *
       * <code>int32 use_icon = 8;</code>
       */
      public Builder clearUseIcon() {
        
        useIcon_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.client_info)
    }

    // @@protoc_insertion_point(class_scope:common.client_info)
    private static final net.protol.common.Common.client_info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.protol.common.Common.client_info();
    }

    public static net.protol.common.Common.client_info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<client_info>
        PARSER = new com.google.protobuf.AbstractParser<client_info>() {
      public client_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new client_info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<client_info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<client_info> getParserForType() {
      return PARSER;
    }

    public net.protol.common.Common.client_info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface match_playerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.match_player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 country = 3;</code>
     */
    int getCountry();

    /**
     * <code>int32 icon = 4;</code>
     */
    int getIcon();

    /**
     * <code>int32 race = 5;</code>
     */
    int getRace();

    /**
     * <code>int32 race_level = 6;</code>
     */
    int getRaceLevel();
  }
  /**
   * Protobuf type {@code common.match_player}
   */
  public  static final class match_player extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.match_player)
      match_playerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use match_player.newBuilder() to construct.
    private match_player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private match_player() {
      uid_ = 0;
      name_ = "";
      country_ = 0;
      icon_ = 0;
      race_ = 0;
      raceLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private match_player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              country_ = input.readInt32();
              break;
            }
            case 32: {

              icon_ = input.readInt32();
              break;
            }
            case 40: {

              race_ = input.readInt32();
              break;
            }
            case 48: {

              raceLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.protol.common.Common.internal_static_common_match_player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.protol.common.Common.internal_static_common_match_player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.protol.common.Common.match_player.class, net.protol.common.Common.match_player.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 3;
    private int country_;
    /**
     * <code>int32 country = 3;</code>
     */
    public int getCountry() {
      return country_;
    }

    public static final int ICON_FIELD_NUMBER = 4;
    private int icon_;
    /**
     * <code>int32 icon = 4;</code>
     */
    public int getIcon() {
      return icon_;
    }

    public static final int RACE_FIELD_NUMBER = 5;
    private int race_;
    /**
     * <code>int32 race = 5;</code>
     */
    public int getRace() {
      return race_;
    }

    public static final int RACE_LEVEL_FIELD_NUMBER = 6;
    private int raceLevel_;
    /**
     * <code>int32 race_level = 6;</code>
     */
    public int getRaceLevel() {
      return raceLevel_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (country_ != 0) {
        output.writeInt32(3, country_);
      }
      if (icon_ != 0) {
        output.writeInt32(4, icon_);
      }
      if (race_ != 0) {
        output.writeInt32(5, race_);
      }
      if (raceLevel_ != 0) {
        output.writeInt32(6, raceLevel_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (country_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, country_);
      }
      if (icon_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, icon_);
      }
      if (race_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, race_);
      }
      if (raceLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, raceLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.protol.common.Common.match_player)) {
        return super.equals(obj);
      }
      net.protol.common.Common.match_player other = (net.protol.common.Common.match_player) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getName()
          .equals(other.getName());
      result = result && (getCountry()
          == other.getCountry());
      result = result && (getIcon()
          == other.getIcon());
      result = result && (getRace()
          == other.getRace());
      result = result && (getRaceLevel()
          == other.getRaceLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry();
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon();
      hash = (37 * hash) + RACE_FIELD_NUMBER;
      hash = (53 * hash) + getRace();
      hash = (37 * hash) + RACE_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getRaceLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.protol.common.Common.match_player parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.match_player parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.match_player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.match_player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.match_player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.protol.common.Common.match_player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.protol.common.Common.match_player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.match_player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.match_player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.match_player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.protol.common.Common.match_player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.protol.common.Common.match_player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.protol.common.Common.match_player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.match_player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.match_player)
        net.protol.common.Common.match_playerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.protol.common.Common.internal_static_common_match_player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.protol.common.Common.internal_static_common_match_player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.protol.common.Common.match_player.class, net.protol.common.Common.match_player.Builder.class);
      }

      // Construct using net.protol.common.Common.match_player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        name_ = "";

        country_ = 0;

        icon_ = 0;

        race_ = 0;

        raceLevel_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.protol.common.Common.internal_static_common_match_player_descriptor;
      }

      public net.protol.common.Common.match_player getDefaultInstanceForType() {
        return net.protol.common.Common.match_player.getDefaultInstance();
      }

      public net.protol.common.Common.match_player build() {
        net.protol.common.Common.match_player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.protol.common.Common.match_player buildPartial() {
        net.protol.common.Common.match_player result = new net.protol.common.Common.match_player(this);
        result.uid_ = uid_;
        result.name_ = name_;
        result.country_ = country_;
        result.icon_ = icon_;
        result.race_ = race_;
        result.raceLevel_ = raceLevel_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.protol.common.Common.match_player) {
          return mergeFrom((net.protol.common.Common.match_player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.protol.common.Common.match_player other) {
        if (other == net.protol.common.Common.match_player.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getCountry() != 0) {
          setCountry(other.getCountry());
        }
        if (other.getIcon() != 0) {
          setIcon(other.getIcon());
        }
        if (other.getRace() != 0) {
          setRace(other.getRace());
        }
        if (other.getRaceLevel() != 0) {
          setRaceLevel(other.getRaceLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.protol.common.Common.match_player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.protol.common.Common.match_player) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int country_ ;
      /**
       * <code>int32 country = 3;</code>
       */
      public int getCountry() {
        return country_;
      }
      /**
       * <code>int32 country = 3;</code>
       */
      public Builder setCountry(int value) {
        
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 country = 3;</code>
       */
      public Builder clearCountry() {
        
        country_ = 0;
        onChanged();
        return this;
      }

      private int icon_ ;
      /**
       * <code>int32 icon = 4;</code>
       */
      public int getIcon() {
        return icon_;
      }
      /**
       * <code>int32 icon = 4;</code>
       */
      public Builder setIcon(int value) {
        
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 icon = 4;</code>
       */
      public Builder clearIcon() {
        
        icon_ = 0;
        onChanged();
        return this;
      }

      private int race_ ;
      /**
       * <code>int32 race = 5;</code>
       */
      public int getRace() {
        return race_;
      }
      /**
       * <code>int32 race = 5;</code>
       */
      public Builder setRace(int value) {
        
        race_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 race = 5;</code>
       */
      public Builder clearRace() {
        
        race_ = 0;
        onChanged();
        return this;
      }

      private int raceLevel_ ;
      /**
       * <code>int32 race_level = 6;</code>
       */
      public int getRaceLevel() {
        return raceLevel_;
      }
      /**
       * <code>int32 race_level = 6;</code>
       */
      public Builder setRaceLevel(int value) {
        
        raceLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 race_level = 6;</code>
       */
      public Builder clearRaceLevel() {
        
        raceLevel_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.match_player)
    }

    // @@protoc_insertion_point(class_scope:common.match_player)
    private static final net.protol.common.Common.match_player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.protol.common.Common.match_player();
    }

    public static net.protol.common.Common.match_player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<match_player>
        PARSER = new com.google.protobuf.AbstractParser<match_player>() {
      public match_player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new match_player(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<match_player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<match_player> getParserForType() {
      return PARSER;
    }

    public net.protol.common.Common.match_player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_test4_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_test4_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_test3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_test3_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_client_info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_client_info_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_match_player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_match_player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\006common\"1\n\005test4\022\t\n\001f\030\001 \001" +
      "(\005\022\013\n\003ccc\030\002 \001(\t\022\020\n\010cmd_data\030\003 \001(\t\"-\n\005tes" +
      "t3\022\t\n\001d\030\001 \001(\005\022\031\n\002cc\030\002 \001(\0132\r.common.test4" +
      "\"2\n\013client_info\022\021\n\tuser_name\030\007 \001(\t\022\020\n\010us" +
      "e_icon\030\010 \001(\005\"j\n\014match_player\022\013\n\003uid\030\001 \001(" +
      "\005\022\014\n\004name\030\002 \001(\t\022\017\n\007country\030\003 \001(\005\022\014\n\004icon" +
      "\030\004 \001(\005\022\014\n\004race\030\005 \001(\005\022\022\n\nrace_level\030\006 \001(\005" +
      "B\023\n\021net.protol.commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_test4_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_test4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_test4_descriptor,
        new java.lang.String[] { "F", "Ccc", "CmdData", });
    internal_static_common_test3_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_test3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_test3_descriptor,
        new java.lang.String[] { "D", "Cc", });
    internal_static_common_client_info_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_client_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_client_info_descriptor,
        new java.lang.String[] { "UserName", "UseIcon", });
    internal_static_common_match_player_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_match_player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_match_player_descriptor,
        new java.lang.String[] { "Uid", "Name", "Country", "Icon", "Race", "RaceLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
